### ISSUE TITLE
README should have an example for including a css preprocessor (i.e. SASS) in the build process

### ISSUE THREAD

**Issue by PeteJodo** [wbyoung/babel-plugin-transform-postcss#12]
I'm currently trying to figure this out since the [babel-plugin-css-modules](https://github.com/michalkvasnicak/babel-plugin-css-modules-transform) didn't cover my requirements . At a glance, it looks like the preprocessor has to be ran entirely before babel which will then pick up the built `.css` files. Is there no way to do it all together? I'd prefer not to build intermediate `.css` files.

**Comment by wbyoung** [comment]
No, you should be able to configure it such that your JS build will use this babel transorm and apply all PostCSS transforms to the imported CSS and result in a mapping of selector names to transformed selector names.

You can then run whatever you choose to actually generate the CSS, but hopefully it uses the same config.

You should probably use tools that work with `postcss-load-config` and have a `postcss.config.js`.

If you get an example project working, I'll happily link to it in the docs, but would prefer to leave the docs basic as this isn't really the right place to document more specific configurations (or get answers since I don't have them :wink:).

**Comment by PeteJodo** [comment]
After a little more research, I didn't realize what PostCSS really was. I see now that I can include some plugins that mimic SCSS for the most part but isn't actually SCSS. Unfortunately, I can't use that due to some dependencies. Thanks for the help though!

**Comment by PeteJodo** [comment]
@wbyoung it looks like your plugin only looks for [`.css` files](https://github.com/wbyoung/babel-plugin-transform-postcss/blob/master/src/plugin.js#L55).

I'm using [PreCSS](https://github.com/jonathantneal/precss) like:
```js
require('precss')({
    import: { extension: 'scss' }
})
```
along with the [postcss-scss](https://github.com/postcss/postcss-scss) parser because I'd like to keep `.scss` files.

Just want to confirm, this set up won't work with your plugin, right?

**Comment by wbyoung** [comment]
@PeteJodo it is currently only set up for `.css` files, but would be really easy to add an option to allow [overriding the extensions](https://github.com/wbyoung/babel-plugin-transform-postcss/blob/24d5a1ae51569e9ef4d13401605682092c8633d4/src/plugin.js#L55).

**Comment by gajus** [comment]
> @PeteJodo it is currently only set up for .css files, but would be really easy to add an option to allow overriding the extensions.

Looks like this have not been done. :-(

**Comment by wbyoung** [comment]
@gajus no, this has not been done yet, but I'd happily accept a PR to accept an option to override the extensions.

**Comment by igor-ribeiro** [comment]
@wbyoung It's as simple as changing this: https://github.com/wbyoung/babel-plugin-transform-postcss/blob/master/src/plugin.js#L55?

**Comment by wbyoung** [comment]
@igor-ribeiro it should be, yes.

**Comment by igor-ribeiro** [comment]
I did it, I'm creating a PR

**Comment by nescalante** [comment]
Is this released on any version?
I am not seeing it in latest
