### ISSUE TITLE
Specify PostCSS config file

### ISSUE THREAD

**Issue by chrisngobanh** [wbyoung/babel-plugin-transform-postcss#40]
It appears that the plugin searches for a PostCSS config file to load in the same directory that the imported CSS file resides, or in the root directory of the project. 

There should be an option in the plugin to specify where to find the project's PostCSS config file.

**Comment by wbyoung** [comment]
This uses `postcss-load-config`which is hopefully becoming the de facto standard for PostCSS tools.

I'm happy to discuss more here, but I think if you have something custom you need, that it'll have to happen in `postcss-load-config`.

**Comment by chrisngobanh** [comment]
I think you may have misunderstood what I meant. 

When you call the default function of `postcss-load-config`, the second argument specifies which directory to search for the PostCSS config. In our case, we're [searching for the PostCSS config in the same directory as the CSS file that's being processed](https://github.com/wbyoung/babel-plugin-transform-postcss/blob/master/src/postcss-server.js#L77).

For reference, [here's the source code](https://github.com/michael-ciniawsky/postcss-load-config/blob/master/index.js#L40) for the function from `postcss-load-config`.

**Comment by wbyoung** [comment]
Yes, but that's using https://github.com/davidtheclark/cosmiconfig which seems like a pretty sane way to load config files for 90%+ of use cases.

This is more or less what  [the CLI](https://github.com/postcss/postcss-cli/blob/2322cb8d8d8080e9ac00471cd32fd2d6e8515013/index.js#L163) and [`gulp-postcss`](https://github.com/postcss/gulp-postcss/blob/3a1d0df7029a6a6fa4e62f08d0507eac8a96b2e9/index.js#L127) do, but they do have an options to configure the path.

If we add an option, it needs to be part of the babel plugin config options and should probably be named to match consistency with the above linked PRs.

I'm curious about your config setup, though… it still seems as though the defaults should work. Also, it may be worth discussing an environment variable based approach with the `postcss-load-config` team so that there's consistency across all projects using that (rather than us all implementing the same option slightly differently).

**Comment by chrisngobanh** [comment]
I was suggesting to add an option to set the path to find the config, like in the examples you shared. Hope we're on the same page now 👍

**Comment by wbyoung** [comment]
@chrisngobanh do you have the time to work on a PR for this?
